---
abstract: 'An multi-level overridable perl based configuration module'
author:
  - 'Lucas Theisen <lucastheisen@pastdev.com>'
build_requires:
  File::Basename: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Entities
requires:
  Cwd: '0'
  Data::Dumper: '0'
  File::Find: '0'
  File::Spec: '0'
  Log::Any: '0'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/lucastheisen/config-entities
  repository: https://github.com/lucastheisen/config-entities.git
version: '0.01'
